version: '3.9'
services:
  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluent-bit
    #restart: always
    network_mode: host
    # user: pfmadm
    volumes:
            # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ./conf/parsers.conf:/fluent-bit/etc/parsers.conf
    - ./conf/filter.lua:/fluent-bit/etc/filter.lua
      #- /var/log:/data/log:ro
    - ./data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
